name: Build

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: codestyle
      run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/game/*.c src/game/*.h src/main/*.c src/menu/*.c src/menu/*.h
